#Window
WIN_HEIGHT = 800
WIN_WIDTH = 1200
WIN_CAPTION = "Weird Scratch game aber Python"
FPS = 60

#Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

#Player
PLAYER_LAYER = 3
PLAYER_WIDTH = 70
PLAYER_HEIGHT = 140
PLAYER_JUMPFORCE = 20
PLAYER_X = 100
PLAYER_Y = 500

#Ground
GROUND_LAYER = 2
GROUND_LEVEL = 700
GROUND_HEIGHT = WIN_HEIGHT - GROUND_LEVEL
GROUND_WIDTH = WIN_WIDTH

#Baseball
BASEBALL_LAYER = 1
BASEBALL_SPEED = 25
BASEBALL_DIAMETER = 75
BASEBALL_X = WIN_WIDTH
BASEBALL_Y = GROUND_LEVEL - BASEBALL_DIAMETER

#Text
TEXT_LAYER = 0
FONT = "ARIAL.TTF"
FONT_SIZE= 50

#Other
GRAVITY = 1
